### ISSUE TITLE
Random respring

### ISSUE THREAD

**Issue by mcproj** [Kaitouiet/FastForwardTime#1]
iPhone X iOS 11.2.1
A random respring occurs 45-75 minute after SpringBoard started, 100% reproduce rate
Mostly happens when a notification arrives on lock screen or swipe up on the bottom of an app to go back to homescreen
No crash log to those resprings is generated

**Comment by Kaitouiet** [comment]
I am aware, will look into it

**Comment by Kaitouiet** [comment]
1.0.3 should fix this, update soon on bigboss.

**Comment by mcproj** [comment]
Installed 1.0.3, but swiping up on the bottom of an app to go back to homescreen still sometime crashes springboard. It happened just now, after a swipe-to-home after a long time(more than 1 hour) lock with an app left open.

**Comment by Kaitouiet** [comment]
update to 1.0.4 and see.

**Comment by mcproj** [comment]
1.0.4 seems to work well. 
Could you make that second hideable when the screen is off/about to be turned off? It will be perfect as this will make it compatible to other tweaks like Semperon.

**Comment by Kaitouiet** [comment]
Can you show me how it looks in semperon?

**Comment by mcproj** [comment]
Semperon is an always-on time display tweak made for oled screen. It keeps the time shown on the screen when the screen is turned off. 
It uses its own 1-minute refresh mechanism. When the screen shuts down the second is just frozen.
